name: Module Bug Report
description: Report a bug with a Takaro module
title: "[Bug] "
labels: ["bug", "module-issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide some basic information to help us fix it.

  - type: input
    id: module_name
    attributes:
      label: Module Name
      description: Which module has the issue?
      placeholder: e.g., Limon_8ball, Mad_BlackJack
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug you encountered
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: How to reproduce (optional)
      description: If possible, tell us how to trigger this bug
      placeholder: |
        1. Use command /example
        2. Wait for response
        3. Error occurs

  - type: textarea
    id: additional_info
    attributes:
      label: Error messages or screenshots (optional)
      description: Any errors, logs, or screenshots that might help
      placeholder: Paste error messages or drag images here...